#
# ==============
# validateSyncedSteemAccountAuths.sk
# ==============
# validateSyncedSteemAccountAuths.sk is part of the STEEM.CRAFT core functions.
# ==============

#
# > Function - validateSyncedSteemAccountAuths
# > Returns true if the synced steem account is connected properly, if not,
# > false is returned.
# > Parameters:
# > <offline player>the player which should be checked for being synced
# > <SteemJ account>a SteemJ account object
# > Returns:
# > <boolean>true=synced | false=not synced
function validateSyncedSteemAccountAuths(player:offline player, account:object) :: boolean:
  #
  # > Check if the given steem account authorized the server Steem account.
  set {_accountdata} to getAccount({_account})
  if {_account} is set:
    set {_neededauth} to getServerAccountName()
    loop ...{_account}.getPosting().getAccountAuths().keySet():
      if "%loop-value%" is {_neededauth}:
        return true
    return false
