#
# ==============
# validateSyncedSteemAccountUUID.sk
# ==============
# validateSyncedSteemAccountUUID.sk is part of the STEEM.CRAFT core functions.
# ==============

import:
  com.fasterxml.jackson.databind.ObjectMapper

#
# > Function - validateSyncedSteemAccountUUID
# > Returns true if the synced steem account is connected properly, if not,
# > false is returned.
# > Parameters:
# > <offline player>the player which should be checked for being synced
# > <SteeJ account>a SteemJ account object
# > Returns:
# > <boolean>true=synced | false=not synced
function validateSyncedSteemAccountUUID(player:offline player, account:object) :: boolean:
  #
  # > Check if the given steem account matches up with the given minecraft user.
  if {_account} is set:
    set {_json} to {_account}.getJsonMetadata()
    set {_objectMapper} to new ObjectMapper()
    set {_jsonNode} to {_objectMapper}.readTree({_json})

    #
    # > The profile needs the minecraftuuid value set to the ingame uuid.
    # > If this value doesn't match, it will return false.
    # > The JsonMetadata of the account should contain at least the following data:
    # > {"profile":{"minecraftuuid":"minecraft uuid value of the player"}}
    set {_steemuuid} to {_jsonNode}.get("profile").get("minecraftuuid").textValue()

    #
    # > The uuid of a {_player} has to be stored in a variable
    # > before it can be used to check for the same string.
    set {_uuid} to uuid of {_player}
    if {_uuid} is {_steemuuid}:
      return true
  return false
