#
# ==============
# GetSteemWorldShortName.sk
# ==============
# GetSteemWorldShortName.sk is part of the STEEM.CRAFT addons.
# ==============

#
# > Function - GetSteemWorldShortName
# > Returns the short steem world name.
# > Parameters:
# > <world>the world to which the short name should be returned
function GetSteemWorldShortName(world:world) :: text:
  set {_name} to "%{_world}%"
  replace all "steemworlds-" with "" in {_name}
  return {_name}
